=== clenk/stix2.0/schemas/common/bundle.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "bundle",
  "description": "A bundle is a collection of STIX Objects grouped together to enable them to be exchanged across interoperable systems.",
  "type": "object",
  "properties": {
	"type": {
	  "type": "string",
	  "description": "The type of this object, which MUST be the literal `bundle`.",
	  "enum": ["bundle"]
	},
	"id": {
	  "$ref": "identifier.json",
	  "description": "An identifier for this bundle."
	},
	"spec_version": {
	   "type": "string",
       "enum": ["2.0"],
	   "description": "The version of the STIX specification used to represent the content in this bundle."
	},
	"attack_patterns": {
	  "type": "array",
	  "description": "Specifies a set of one or more Attack Patterns.",
	  "items": {"$ref": "../sdos/attack-pattern.json"}
	},
	"campaigns": {
	  "type": "array",
	  "description": "Specifies a set of one or more Campaigns.",
	  "items": {"$ref": "../sdos/campaign.json"}
	},
	"courses_of_action": {
	  "type": "array",
	  "description": "Specifies a set of one or more Courses of Action that could be taken in regard to one of more cyber threats.",
	  "items": {"$ref": "../sdos/course-of-action.json"}
	},
    "incidents": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Incidents.",
	  "items": {"$ref": "../sdos/incident.json"}
	},
	"indicators": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Indicators.",
	  "items": {"$ref": "../sdos/indicator.json"}
	},
	"infrastructures": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat malicious infrastructure.",
	  "items": {"$ref": "../sdos/infrastructure.json"}
	},
	"intrusion_sets": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Intrusion Sets.",
	  "items": {"$ref": "../sdos/intrusion-set.json"}
	},
	"malware": {
	  "type": "array",
	  "description": "Specifies a set of one or more Malware TTPs.",
	  "items": {"$ref": "../sdos/malware.json"}
	},
	"marking_definitions": {
	  "type": "array",
	  "description": "Specifies a set of one or more Marking Definitions.",
	  "items": {"$ref": "marking-definition.json"}
	},
	"observed_data": {
	  "type": "array",
	  "description": "Specifies a set of one or more piece of Observed Data.",
	  "items": {"$ref": "../sdos/observed-data.json"}
	},
	"relationships": {
	  "type": "array",
	  "description": "Specifies a set of one or more relationships between SDOs.",
	  "items": {"$ref": "../sros/relationship.json"}
	},
	"reports": {
	  "type": "array",
	  "description": "Specifies a set of one or more reports.",
	  "items": {"$ref": "../sdos/report.json"}
	},
	"sightings": {
	  "type": "array",
	  "description": "Specifies a set of one or more sightings.",
	  "items": {"$ref": "../sros/sighting.json"}
	},
	"sources": {
	  "type": "array",
	  "description": "Specifies a set of one or more individual or organizational sources.",
	  "items": {"$ref": "../sdos/source.json"}
	},
	"threat_actors": {
	  "type": "array",
	  "description": "Specifies a set of one or more Threat Actors.",
	  "items": {"$ref": "../sdos/threat-actor.json"}
	},
    "tools": {
	  "type": "array",
	  "description": "Specifies a set of one or more Tools.",
	  "items": {"$ref": "../sdos/tool.json"}
	},
    "victim_targets": {
	  "type": "array",
	  "description": "Specifies a set of one or more Victim Targets.",
	  "items": {"$ref": "../sdos/victim-target.json"}
	},
    "vulnerabilities": {
	  "type": "array",
	  "description": "Specifies a set of one or more Vulnerabilities.",
	  "items": {"$ref": "../sdos/vulnerability.json"}
	},
    "custom_objects": {
	  "type": "array",
	  "description": "Specifies a list of one or more custom objects.",
	  "items": {
        "type": "object"
      }
	}
  },
  "required": ["type", "id", "spec_version"]
}

=== clenk/stix2.0/examples/idioms/malware-characterization-using-maec.json
{
  "type": "bundle",
  "id": "bundle--2b8fb66f-b6b3-4d40-865a-33e4a5ee1246",
  "spec_version": "2.0",
  
  "malware": [
    {
      "type": "malware",
	  "id": "malware--bce53fe4-d5ac-4f0b-9675-d728a60675a2",
	  "version": 1,
	  "created": "2016-08-23T18:05:49.371000",
	  "modified": "2016-08-23T18:05:49.371000",
	  "name": "Poison Ivy Variant v4392-acc",
	  "labels": [
		"remote-access-trojan"
	  ]
    }
  ]
}

=== clenk/stix2.0/examples/idioms/plain-wrapper-around-multiple-reports.json
{
  "type": "bundle",
  "id": "bundle--50578bc7-bb17-4f31-abf2-d5827d131368",
  "spec_version": "2.0",
  
  "campaigns": [
    {
      "type": "campaign",
      "id": "campaign--1855cb8a-d96c-4859-a450-abb1e7c061f2",
      "version": 1,
      "created": "2015-05-07T14:22:14.760144Z",  
	  "modified": "2015-05-07T14:22:14.760144Z",
      "name": "Campaign against ICS"
    }
  ],
  
  "sources": [
    {
      "type": "source",
      "id": "source--d7ae33db-0111-45e7-9adb-75a7b081859a",
	  "version": 1,
	  "created": "2015-03-02T13:15:18.793213Z",
	  "modified": "2015-03-02T13:15:18.793213Z",
      "name": "Government Sharing Program - GSP",
	  "entity_class": "organization",
	  "sector": "government-national"
    }
  ],
  
  "malware": [
    {
      "type": "malware",
      "id": "malware--66647c79-5766-4ca7-ab8a-a579056e3c83",
      "version": 1,
      "created": "2015-05-07T14:22:14.760302Z",
	  "modified": "2015-05-07T14:22:14.760302Z",
      "name": "DrownedRat",
      "labels": ["remote-access-trojan"] 
    }
  ],
  
  "reports": [
   {
      "type": "report",   
      "id": "report--41e59083-e2d9-4e4b-9095-ebd1eb2f9350",
      "version": 1,
      "created": "2015-05-07T14:22:14.760467Z",
	  "modified": "2015-05-07T14:22:14.760467Z",
      "report_refs": [
		"source--d7ae33db-0111-45e7-9adb-75a7b081859a",
		"campaign--1855cb8a-d96c-4859-a450-abb1e7c061f2"
	  ],
      "name": "Report on Adversary Alpha's Campaign against the Industrial Control Sector",
      "description": "Adversary Alpha has a campaign against the ICS sector!",
      "labels": ["campaign"],
      "published": "2015-01-01T12:42:16.157317Z"      
    },
    
    {
      "type": "report",   
      "id": "report--bd9cdb35-16a3-4b20-927a-3ae97d5ec4b9",
      "version": 1,
      "created": "2015-05-07T14:22:14.760756Z",
	  "modified": "2015-05-07T14:22:14.760756Z",
      "report_refs": [
		"source--d7ae33db-0111-45e7-9adb-75a7b081859a",
		"malware--66647c79-5766-4ca7-ab8a-a579056e3c83"
	  ],
      "name": "Indicators for Malware DrownedRat",
      "description": "Adversary Alpha has a campaign against the ICS sector!",
      "labels": [
		"indicator",
		"malware"
	  ],
	  "published": "2015-01-01T12:42:16.157317Z"      
    }
  ]
}

=== clenk/stix2.0/examples/idioms/malware-used-during-an-incident.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  
  "incidents": [
    {
      "type": "incident",
      "id": "incident--d6f8f6d6-e9ea-4d8f-b066-20a492ac9561",
      "version": 1,
      "created": "2014-02-20T09:00:00.000000Z",
	  "modified": "2014-02-20T09:00:00.000000Z",
      "name": "Poison Ivy detection",
      "description":  "Detected Poison Ivy beaconing through perimeter firewalls"	  
    }
  ],
  
  "malware": [
    {
      "type": "malware",
      "id": "malware--1b75ee8f-14d6-819a-d729-09ab52c91fdb",
      "version": 1,
      "created": "2014-02-20T09:00:00.000000Z",
	  "modified": "2014-02-20T09:00:00.000000Z",
      "name": "Poison Ivy",
      "labels": ["remote-access-trojan"] 
    }
  ],
  
  "relationships": [
    {
      "type": "relationship",
      "id": "relationship--da2b5f04-a0f8-4063-9c18-f925c7af94bb",
      "version": 1,
      "created": "2014-02-20T09:00:00.000000Z", 
	  "modified": "2014-02-20T09:00:00.000000Z",
      "name": "related-to",
      "source_ref": "incident--d6f8f6d6-e9ea-4d8f-b066-20a492ac9561",
      "target_ref": "malware--1b75ee8f-14d6-819a-d729-09ab52c91fdb"      
    }  
  ]
}

=== clenk/stix2.0/examples/idioms/defining-campaigns-vs-threat-actors.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  
  "campaigns": [
    {
        "type": "campaign",
        "id": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
        "version": 1,
        "created": "2014-08-08T15:50:10.983728Z",
        "modified": "2014-08-08T15:50:10.983728Z",		
        "name": "Compromise of ATM Machines"
    }
  ],
  
  "relationships": [
    {
        "type": "relationship",
        "id": "relationship--d07b0cc3-11eb-4906-9e0b-4bcca5f408e4",
        "version": 1,
        "created": "2014-08-08T15:50:10.983728Z", 
		"modified": "2014-08-08T15:50:10.983728Z",
        "name": "targets", 
        "source_ref": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
        "target_ref": "victim-target--2d1c6ab3-5e4e-48ac-a32b-f0c01c2836a8"        
    },
    
    {
        "type": "relationship",
        "id": "relationship--5cc8ddc2-4346-4ba1-a997-1b42872b02b0",
        "version": 1,
        "created": "2014-08-08T15:50:10.983728Z",
        "modified": "2014-08-08T15:50:10.983728Z",		
        "name": "attributed-to",
        "source_ref": "campaign--e5268b6e-4931-42f1-b379-87f48eb41b1e",
        "target_ref": "threat-actor--56f3f0db-b5d5-431c-ae56-c18f02caf500"        
    } 
  ],
  
  "threat_actors": [
    {
        "type": "threat-actor",
        "id": "threat-actor--56f3f0db-b5d5-431c-ae56-c18f02caf500",
        "version": 1,
        "created": "2014-08-08T15:50:10.983629Z",
		"modified": "2014-08-08T15:50:10.983629Z",
        "name": "People behind the ATM compromise",
		"labels": ["thief"],
		"entity_class": "unknown"
    }
  ],
  
  "victim_targets": [
    {
        "type": "victim-target",
        "id": "victim-target--2d1c6ab3-5e4e-48ac-a32b-f0c01c2836a8",
        "version": 1,
        "created": "2014-08-08T15:50:10.983464Z",
		"modified": "2014-08-08T15:50:10.983464Z",
		"name": "XYZ Bank",
		"description": "Customer PII and Financial Data were targeted.",
		"entity_class": "organization",
		"sectors": ["financial-services"]
    }
  ]
}

=== clenk/stix2.0/examples/idioms/malicious-e-mail-indicator-with-attachment.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "attack_patterns": [
    {
        "type": "attack-pattern",
        "id": "attack-pattern--d7b066aa-4091-4276-a142-29d5d81c3484",
        "version": 1,
        "created": "2014-10-31T15:52:13.126765Z",
		"modified": "2014-10-31T15:52:13.126765Z",
        "name": "Phishing",
        "external-references": [
          {
          "source_name": "CAPEC",
          "external_id": "capec-98"
          }
        ]
    }
  ],

  "indicators": [
    {
        "type": "indicator",
        "id": "indicator--8cf9236f-1b96-493d-98be-0c1c1e8b62d7",
        "version": 1,
        "created": "2014-10-31T15:52:13.127931Z",
		"modified": "2014-10-31T15:52:13.127931Z",
        "name": "Malicious Email",		
        "labels": ["malicious-activity"],       
		"valid_from": "2014-10-31T15:52:13.127931Z",
		"pattern": "message-object:extended_properties['email-message'].subject MATCHES \/^\\[IMPORTANT\\] Please Review Before\/ AND message-object:extended_properties['email-message'].attachments[*].name MATCHES \/^Final Report.+\\.exe$\/"
    }
  ],
  
  "relationships": [
       {
         "type": "relationship",
         "id": "relationship--e983dad5-7c88-444a-9f78-cf31dbfae2bd",
         "version": 1,
         "created": "2014-10-31T15:52:13.126765Z",
		 "modified": "2014-10-31T15:52:13.126765Z",
         "name": "indicates",
         "source_ref": "indicator--8cf9236f-1b96-493d-98be-0c1c1e8b62d7",
         "target_ref": "attack-pattern--d7b066aa-4091-4276-a142-29d5d81c3484"         
     }
  ]
}
