=== clenk/stix2.0/schemas/common/bundle.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "bundle",
  "description": "A bundle is a collection of STIX Objects grouped together to enable them to be exchanged across interoperable systems.",
  "type": "object",
  "properties": {
	"type": {
	  "type": "string",
	  "description": "The type of this object, which MUST be the literal `bundle`.",
	  "enum": ["bundle"]
	},
	"id": {
	  "$ref": "identifier.json",
	  "description": "An identifier for this bundle."
	},
	"spec_version": {
	   "type": "string",
       "enum": ["2.0"],
	   "description": "The version of the STIX specification used to represent the content in this bundle."
	},
	"attack_patterns": {
	  "type": "array",
	  "description": "Specifies a set of one or more Attack Patterns.",
	  "items": {"$ref": "../sdos/attack-pattern.json"}
	},
	"campaigns": {
	  "type": "array",
	  "description": "Specifies a set of one or more Campaigns.",
	  "items": {"$ref": "../sdos/campaign.json"}
	},
	"courses_of_action": {
	  "type": "array",
	  "description": "Specifies a set of one or more Courses of Action that could be taken in regard to one of more cyber threats.",
	  "items": {"$ref": "../sdos/course-of-action.json"}
	},
    "incidents": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Incidents.",
	  "items": {"$ref": "../sdos/incident.json"}
	},
	"indicators": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Indicators.",
	  "items": {"$ref": "../sdos/indicator.json"}
	},
	"infrastructures": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat malicious infrastructure.",
	  "items": {"$ref": "../sdos/infrastructure.json"}
	},
	"intrusion_sets": {
	  "type": "array",
	  "description": "Specifies a set of one or more cyber threat Intrusion Sets.",
	  "items": {"$ref": "../sdos/intrusion-set.json"}
	},
	"malware": {
	  "type": "array",
	  "description": "Specifies a set of one or more Malware TTPs.",
	  "items": {"$ref": "../sdos/malware.json"}
	},
	"marking_definitions": {
	  "type": "array",
	  "description": "Specifies a set of one or more Marking Definitions.",
	  "items": {"$ref": "marking-definition.json"}
	},
	"observed_data": {
	  "type": "array",
	  "description": "Specifies a set of one or more piece of Observed Data.",
	  "items": {"$ref": "../sdos/observed-data.json"}
	},
	"relationships": {
	  "type": "array",
	  "description": "Specifies a set of one or more relationships between SDOs.",
	  "items": {"$ref": "../sros/relationship.json"}
	},
	"reports": {
	  "type": "array",
	  "description": "Specifies a set of one or more reports.",
	  "items": {"$ref": "../sdos/report.json"}
	},
	"sightings": {
	  "type": "array",
	  "description": "Specifies a set of one or more sightings.",
	  "items": {"$ref": "../sros/sighting.json"}
	},
	"sources": {
	  "type": "array",
	  "description": "Specifies a set of one or more individual or organizational sources.",
	  "items": {"$ref": "../sdos/source.json"}
	},
	"threat_actors": {
	  "type": "array",
	  "description": "Specifies a set of one or more Threat Actors.",
	  "items": {"$ref": "../sdos/threat-actor.json"}
	},
    "tools": {
	  "type": "array",
	  "description": "Specifies a set of one or more Tools.",
	  "items": {"$ref": "../sdos/tool.json"}
	},
    "victim_targets": {
	  "type": "array",
	  "description": "Specifies a set of one or more Victim Targets.",
	  "items": {"$ref": "../sdos/victim-target.json"}
	},
    "vulnerabilities": {
	  "type": "array",
	  "description": "Specifies a set of one or more Vulnerabilities.",
	  "items": {"$ref": "../sdos/vulnerability.json"}
	},
    "custom_objects": {
	  "type": "array",
	  "description": "Specifies a list of one or more custom objects.",
	  "items": {
        "type": "object"
      }
	}
  },
  "required": ["type", "id", "spec_version"]
}

=== clenk/stix2.0/examples/idioms/yara-test-mechanism.json
{
  "type": "bundle",
  "id": "bundle--ea99d4d4-1ae7-4120-9ebe-67ed4783fb36",
  "spec_version": "2.0",
  
  "indicators":[
    {
		"type": "indicator",
		"id": "indicator--567b201c-4fd5-4bde-a5db-42abc340807a",
		"version": 1,
		"created": "2014-06-20 15:16:56.987616",
		"modified": "2014-06-20 15:16:56.987616",
		"name": "silent_banker",
		"pattern": "\\nrule silent_banker : banker\\n{\\n    meta:\\n        description = \"This is just an example\"\\n        thread_level = 3\\n        in_the_wild = true\\n\\n    strings:\\n        $a = {6A 40 68 00 30 00 00 6A 14 8D 91}\\n        $b = {8D 4D B0 2B C1 83 C0 27 99 6A 4E 59 F7 F9}\\n        $c = \"UVODFRYSIHLNWPEJXQZAKCBGMT\"\\n\\n    condition:\\n        $a or $b or $c\\n}\\n",
		"pattern_lang": "yara",
		"description": "This is just an example.",
		"valid_from": "2014-06-20 15:16:56.987616",
		"labels":["malicious-activity"],
		"external_references":[
		  {
			"source_name": "yara",
			"url": "http:\/\/plusvic.github.io\/yara\/"
		  }	
		]
	}
  ]
}

=== clenk/stix2.0/examples/idioms/linking-an-indicator-to-kill-chain-phase.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "indicators": [
    {
        "type": "indicator",
        "id": "indicator--efe1dec4-2f86-44ce-9977-543d15507892",
        "version": 1,
        "created": "2014-10-09T21:38:50.631509Z",
        "modified": "2014-10-09T21:38:50.631509Z",
        "name": "Malicious executable",
        "labels": ["malicious-activity"],
        "description": "Resident binary which implements infostealing and credit card grabber",
        "pattern": "crypt_1_sell23-09.exe_",
        "valid_from": "2014-10-09T21:38:50.631509Z",
        "kill_chain_phases": [
        {
            "kill_chain_name": "Organization-specific Kill Chain",
            "phase_name": "Infect Machine"
        },
        {
            "kill_chain_name": "Organization-specific Kill Chain",
            "phase_name": "Exfiltrate Data"
        }
        ]        
    }
   ]
}

=== clenk/stix2.0/examples/idioms/indicator-to-campaign-relationship.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "campaigns": [
    {
        "type": "campaign",
        "id": "campaign--b549a58c-afd9-4847-85c3-5be13d56d3cc",
        "version": 1,
        "created": "2014-09-09T19:58:39.609000Z",
		"modified": "2014-09-09T19:58:39.609000Z",
        "name": "Operation Omega"
    }
  ],

  "indicators": [
    {
        "type": "indicator",
        "id": "indicator--c43a0a05-e8d2-4f64-ae37-3f3fb153f8d9",
        "version": 1,
        "created": "2014-09-09T19:58:39.609000Z",
		"modified": "2014-09-09T19:58:39.609000Z",
        "labels": ["malicious-activity"],
        "pattern": "ipv4addr-object.value EQ '10.0.0.0'",
		"pattern_lang": "cybox",
		"valid_from": "2014-09-09T19:58:39.609000Z"
    }
  ],
  
  "relationships": [
    {
        "type": "relationship",
        "id": "relationship--eca24e47-2259-4850-9705-fd1065c77236",
        "version": 1,
        "relationship_type": "indicates",
        "created": "2014-09-09T19:58:39.609000Z",
		"modified": "2014-09-09T19:58:39.609000Z",
        "source_ref": "indicator--c43a0a05-e8d2-4f64-ae37-3f3fb153f8d9",
        "target_ref": "campaign--b549a58c-afd9-4847-85c3-5be13d56d3cc"        
    }
  ]
}

=== clenk/stix2.0/examples/idioms/file-hash-reputation.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "indicators": [
    {
	    "type": "indicator",
	    "id": "indicator--14975dea-86cd-4211-a5f8-9c2e4daab69a",
	    "created": "2015-12-21T19:59:17Z",
	    "modified": "2015-12-21T19:59:17Z",
	    "version": 1,
	    "name": "File Reputation for SHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
	    "labels": ["malicious-activity"],
	    "pattern": "file-object:hashes.sha-256 EQ 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'",
		"pattern_lang": "cybox",
	    "valid_from": "2015-12-21T19:59:17Z"
    }
   ],
   
  "malware": [
    {
        "type": "malware",
        "id": "malware--23e715a9-24c8-4b21-ba5b-f564d2edc660",
        "version": 1,
        "created": "2015-12-21T19:59:17Z",
		"modified": "2015-12-21T19:59:17Z",
        "name": "Malicious file",
        "labels": ["spyware"]
    }
   ],
   
   "relationships": [
     {
         "type": "relationship",
         "id": "relationship--21f64c7a-a4fd-4159-b5b7-3658044f7027",
         "version": 1,
         "created": "2015-12-21T19:59:17Z",
		 "modified": "2015-12-21T19:59:17Z",
         "relationship_type": "indicates",
         "source_ref": "indicator--14975dea-86cd-4211-a5f8-9c2e4daab69a",
         "target_ref": "malware--23e715a9-24c8-4b21-ba5b-f564d2edc660"         
     }
   ]
  
}

=== clenk/stix2.0/examples/idioms/course-of-action-to-block-network-traffic.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  
  "courses_of_action": [
    {
        "type": "course-of-action",
        "id": "course-of-action--55f57cc7-ddd5-467b-a3a2-6fd602549d9e",
        "version": 1,
        "created": "2016-08-03T16:27:14Z",
        "modified": "2016-08-03T16:27:14Z",        
		"name": "Block Network Traffic",
		"description": "Added rule to block network traffic coming from this address"        
    }
  ],
  
  "observed_data": [
   {
       "type": "observed-data",
       "id": "observed-data--e04425e4-60a2-4d91-a9f9-0ca956f19edb",
       "version": 1,
       "created": "2016-07-11T12:27:14Z", 
	   "modified": "2016-07-11T12:27:14Z",
	   "first_observed": "2015-12-21T19:00:00Z",
	   "last_observed": "2015-12-21T20:00:00Z",
	   "number_observed": 11,
       "cybox": {
	      "type": "cybox-container",
	      "spec_version": "3.0",
          "objects": [
              {
                "type": "ipv4addr-object",
                "id": "ipv4addr-object--1",
                "value:": "10.10.10.10"
              }
          ]
       }
    }
  ],
  
  "relationships": [
   {
        "type": "relationship",
        "id": "relationship--b2dae1ac-53bf-4d1e-b478-fdc11018c649",
        "version": 1,
        "created": "2016-08-03T16:30:17Z",
        "modified": "2016-08-03T16:30:17Z",
		"name": "related-to",        
        "source_ref": "course-of-action--55f57cc7-ddd5-467b-a3a2-6fd602549d9e",
        "target_ref": "observed-data--e04425e4-60a2-4d91-a9f9-0ca956f19edb"        
    }
  ]
}

=== clenk/stix2.0/examples/idioms/kill-chain.json
{
  "type": "bundle",
  "id": "bundle--91d9b5a2-b63b-431b-ab56-aba30ab36809",
  "spec_version": "2.0",
  
  "indicators":[
	{
		"type": "indicator",
		"id": "indicator--f33c2b75-aa60-4ffb-9829-3746ef233311",
		"version": 1,
		"created": "2014-10-21 21:10:09.423000+00:00",
		"modified": "2014-10-21 21:10:09.423000+00:00",
		"valid_from": "2014-10-21 21:10:09.423000+00:00",
		"kill_chain_phases": [
		{
			"kill_chain_name": "LM Cyber Kill Chain",
			"phase_name": "Actions on Objectives"
		}
		]
	}
  ]
}

=== clenk/stix2.0/examples/idioms/indicator-for-malicious-URL.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "indicators": [
    {
      "type": "indicator",
      "id": "indicator--d81f86b9-975b-bc0b-775e-810c5ad45a4f",
      "version": 1,
      "created": "2014-06-29T13:49:37.079000Z",
	  "modified": "2014-06-29T13:49:37.079000Z",
      "labels": ["malicious-activity"],
      "name": "Malicious site hosting downloader",
      "pattern": "url-object:value = 'http://x4z9arb.cn/4712'",
	  "valid_from": "2014-06-29T13:49:37.079000Z"
    }
  ]
}

=== clenk/stix2.0/examples/idioms/indicator-for-c2-ip-address.json
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",

  "indicators": [
    {
      "type": "indicator",
      "id": "indicator--33fe3b22-0201-47cf-85d0-97c02164528d",
      "version": 1,
      "created": "2014-05-08T09:00:00.000000Z",
	  "modified": "2014-05-08T09:00:00.000000Z",
      "name": "IP Address for known C2 channel",
      "labels": ["malicious-activity"],
      "pattern": "ipv4addr-object:value EQ '10.0.0.0'",
	  "pattern_lang": "cybox",
	  "valid_from": "2014-05-08T09:00:00.000000Z"
    }
   ]  
}
